### PR TITLE
Fixed a bug that a part of text is not visible in RichInput

### LINKED ISSUE #69: Part of text is not visible in RichInput
**Describe the bug**

When text is longer than RichInput, part of the text is not visible.

image

**To Reproduce**

As far as I know, it occurs in any RichInput. (e.g. examples in Storybook)

**Expected behavior**
All the text is visible by scrolling even if the text is longer than RichInput.

**Platform:**
 - OS: MacOS
 - Browser: Chrome
 - Version of this package: 0.20.2

### PR DESCRIPTION
**Pull request by junish**
close #69

Thakns in advance. I'm using this useful library. It helps me very well.

I fixed #69. Then, I checked all examples in storybook. It seems that this pull request does not break the examples. Could you take a look?

### CODE REVIEW

**Comment by inokawa** [comment]
@junish 
Looks nice! Could you fix the tsc error in ci?

**Comment by junish** [comment]
@inokawa I fixed the tsc error. Could you taka a look again? Thanks.

**Review by inokawa — APPROVED** [review]
LGTM

**Comment by inokawa** [comment]
Published in `0.22.4`. Thanks!

**Pull request merged**
